import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    padding: 16,
    backgroundColor: "#F8F9FA",
    borderRadius: 12,
    margin: 16,
    borderWidth: 1,
    borderColor: "#E1E5E9",
  },
  title: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2C3E50",
    marginBottom: 16,
    textAlign: "center",
  },
  warningContainer: {
    backgroundColor: "#FFF3CD",
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#FF9800",
  },
  warningTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#F57C00",
    marginBottom: 8,
  },
  warningText: {
    fontSize: 14,
    color: "#F57C00",
    lineHeight: 20,
    marginBottom: 12,
  },
  infoContainer: {
    backgroundColor: "#E3F2FD",
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#2196F3",
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1565C0",
    marginBottom: 8,
  },
  infoText: {
    fontSize: 14,
    color: "#1565C0",
    lineHeight: 20,
    marginBottom: 4,
  },
  statusContainer: {
    backgroundColor: "#FFFFFF",
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: "#E0E0E0",
  },
  statusTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333333",
    marginBottom: 8,
  },
  statusRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 4,
  },
  statusLabel: {
    fontSize: 14,
    color: "#666666",
  },
  statusValue: {
    fontSize: 14,
    fontWeight: "bold",
  },
  successContainer: {
    backgroundColor: "#E8F5E8",
    padding: 12,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#4CAF50",
  },
  successText: {
    fontSize: 14,
    color: "#2E7D2E",
    lineHeight: 20,
    textAlign: "center",
  },
  actionButton: {
    backgroundColor: "#FF9800",
    padding: 10,
    borderRadius: 6,
    alignItems: "center",
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  linkButton: {
    backgroundColor: "transparent",
    padding: 8,
    borderRadius: 6,
    alignItems: "center",
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#2196F3",
  },
  linkButtonText: {
    color: "#2196F3",
    fontSize: 14,
    fontWeight: "500",
  },
});
